name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Compile Bot
        run: |
          mvn -B clean package
        env:
          BOT_USER: effingerbot
          BOT_TOKEN: ${{secrets.BOT_TOKEN}}

      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "effingerbot"
          heroku_email: "alexander.schamne@gmail.com"
          usedocker: true
          docker_heroku_process_type: 'worker'


